using System.Text.Json;
using System.Text.Json.Serialization;
using ECAssistant.Services;
using ECAssistant.Interfaces;

namespace ECAssistant.Memory;

/// <summary>
/// Vector Memory Store — semantic search over memory entries using embeddings.
/// 
/// No external dependencies. Uses cosine similarity for search.
/// Embeddings are generated by the LLM model (via LLamaSharp) or can be
/// provided externally. Stores vectors + metadata as JSON in the working directory.
/// 
/// Directory structure (created in working directory):
///   ./vecmem/
///     ├── vectors.json      — all vectors + metadata
///     └── config.json       — store settings
/// 
/// Usage:
///   var store = new VectorMemoryStore("./vecmem");
///   await store.InitializeAsync(embeddingGenerator);
///   await store.AddAsync("BugFix:Config", "Fixed config loading issue", "bugs");
///   var results = await store.SearchAsync("config problems", maxResults: 5);
/// </summary>
public class VectorMemoryStore : IDisposable
{
    private readonly string _storeDir;
    private readonly string _vectorsFile;
    private readonly List<VectorEntry> _entries = new();
    private Func<string, Task<float[]>>? _embeddingGenerator;
    private int _vectorDim = 0;
    private bool _initialized = false;
    private readonly ILogger _logger;

    public VectorMemoryStore(string storeDir, ILogger? logger = null)
    {
        _logger = logger ?? new Logger();
        _storeDir = Path.GetFullPath(storeDir);
        _vectorsFile = Path.Combine(_storeDir, "vectors.json");
    }

    /// <summary>Initialize the store — create directory, load existing vectors, set embedding generator.</summary>
    public async Task InitializeAsync(Func<string, Task<float[]>> embeddingGenerator)
    {
        _embeddingGenerator = embeddingGenerator;
        
        if (!Directory.Exists(_storeDir))
            Directory.CreateDirectory(_storeDir);

        await LoadAsync();
        
        // Determine vector dimension from first entry or by generating a test embedding
        if (_entries.Count > 0 && _entries[0].Vector != null)
        {
            _vectorDim = _entries[0].Vector!.Length;
        }
        else
        {
            var testVec = await embeddingGenerator("dimension test");
            _vectorDim = testVec.Length;
        }

        _initialized = true;
        _logger.Info("VecMem", $"Initialized: {_entries.Count} entries, dim={_vectorDim}, dir={_storeDir}");
    }

    /// <summary>Initialize without embedding generator (for load-only mode).</summary>
    public async Task InitializeAsync()
    {
        if (!Directory.Exists(_storeDir))
            Directory.CreateDirectory(_storeDir);
        await LoadAsync();
        if (_entries.Count > 0 && _entries[0].Vector != null)
            _vectorDim = _entries[0].Vector!.Length;
        _initialized = true;
        _logger.Info("VecMem", $"Loaded (no generator): {_entries.Count} entries, dim={_vectorDim}");
    }

    /// <summary>Add an entry with auto-generated embedding.</summary>
    public async Task AddAsync(string key, string content, string category = "general", Dictionary<string, string>? tags = null)
    {
        if (!_initialized || _embeddingGenerator == null)
            throw new InvalidOperationException("Store not initialized with embedding generator.");

        var vector = await _embeddingGenerator($"{key} {content}");
        
        var entry = new VectorEntry
        {
            Id = _entries.Count + 1,
            Key = key,
            Content = content,
            Category = category,
            Tags = tags ?? new(),
            Vector = vector,
            Timestamp = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss")
        };

        _entries.Add(entry);
        await SaveAsync();
        _logger.Info("VecMem", $"Added: {key} (category: {category})");
    }

    /// <summary>Semantic search — finds entries most similar to the query.</summary>
    public async Task<List<VectorSearchResult>> SearchAsync(string query, int maxResults = 5, string? categoryFilter = null)
    {
        if (!_initialized || _embeddingGenerator == null || _entries.Count == 0)
            return new List<VectorSearchResult>();

        var queryVec = await _embeddingGenerator(query);

        var scored = _entries
            .Where(e => string.IsNullOrEmpty(categoryFilter) || e.Category == categoryFilter)
            .Select(e => new VectorSearchResult
            {
                Key = e.Key,
                Content = e.Content,
                Category = e.Category,
                Score = CosineSimilarity(queryVec, e.Vector ?? Array.Empty<float>()),
                Timestamp = e.Timestamp
            })
            .OrderByDescending(x => x.Score)
            .Take(maxResults)
            .ToList();

        _logger.Debug("VecMem", $"Search '{query}': {scored.Count} results, top score: {scored.FirstOrDefault()?.Score:F3}");
        return scored;
    }

    /// <summary>Get search results as formatted string (for LLM injection).</summary>
    public async Task<string> SearchAsTextAsync(string query, int maxResults = 5, string? categoryFilter = null)
    {
        var results = await SearchAsync(query, maxResults, categoryFilter);
        if (results.Count == 0) return "(No semantic matches found.)";

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("### SEMANTIC MEMORY RESULTS:");
        sb.AppendLine();
        foreach (var r in results)
        {
            sb.AppendLine($"[{r.Category}] {r.Key} (score: {r.Score:F2})");
            sb.AppendLine($"  {r.Content.Substring(0, Math.Min(r.Content.Length, 300))}");
            if (r.Content.Length > 300) sb.AppendLine("  ...");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    /// <summary>Count of stored entries.</summary>
    public int Count => _entries.Count;

    /// <summary>Whether the store is initialized.</summary>
    public bool IsInitialized => _initialized;

    /// <summary>Store directory path.</summary>
    public string StorePath => _storeDir;

    /// <summary>Get stats summary.</summary>
    public string GetStats()
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"Vector Memory Stats:");
        sb.AppendLine($"  Entries: {_entries.Count}");
        sb.AppendLine($"  Dimension: {_vectorDim}");
        sb.AppendLine($"  Directory: {_storeDir}");
        if (_entries.Count > 0)
        {
            var byCat = _entries.GroupBy(e => e.Category).OrderByDescending(g => g.Count());
            sb.AppendLine("  By category:");
            foreach (var g in byCat)
                sb.AppendLine($"    {g.Key}: {g.Count()}");
        }
        return sb.ToString();
    }

    /// <summary>Remove an entry by key.</summary>
    public async Task<bool> RemoveAsync(string key)
    {
        var entry = _entries.FirstOrDefault(e => e.Key.Equals(key, StringComparison.OrdinalIgnoreCase));
        if (entry == null) return false;
        _entries.Remove(entry);
        await SaveAsync();
        return true;
    }

    /// <summary>Clear all entries.</summary>
    public async Task ClearAsync()
    {
        _entries.Clear();
        await SaveAsync();
    }

    // ─── Persistence ───────────────────────────────

    private async Task SaveAsync()
    {
        var options = new JsonSerializerOptions { WriteIndented = true };
        var json = JsonSerializer.Serialize(_entries, options);
        await File.WriteAllTextAsync(_vectorsFile, json);
    }

    private async Task LoadAsync()
    {
        if (!File.Exists(_vectorsFile)) return;
        try
        {
            var json = await File.ReadAllTextAsync(_vectorsFile);
            var loaded = JsonSerializer.Deserialize<List<VectorEntry>>(json);
            if (loaded != null) _entries.AddRange(loaded);
        }
        catch (Exception ex)
        {
            _logger.Error("VecMem", $"Failed to load: {ex.Message}");
        }
    }

    // ─── Math ──────────────────────────────────────

    private float CosineSimilarity(float[] a, float[] b)
    {
        if (a.Length == 0 || b.Length == 0 || a.Length != b.Length) return 0f;
        
        float dot = 0, magA = 0, magB = 0;
        for (int i = 0; i < a.Length; i++)
        {
            dot += a[i] * b[i];
            magA += a[i] * a[i];
            magB += b[i] * b[i];
        }
        
        var denom = Math.Sqrt(magA) * Math.Sqrt(magB);
        return denom == 0 ? 0f : (float)(dot / denom);
    }

    public void Dispose() { }
}

// ─── Data Structures ──────────────────────────────

public class VectorEntry
{
    public int Id { get; set; }
    public string Key { get; set; } = "";
    public string Content { get; set; } = "";
    public string Category { get; set; } = "general";
    public Dictionary<string, string> Tags { get; set; } = new();
    public float[]? Vector { get; set; }
    public string Timestamp { get; set; } = "";
}

public class VectorSearchResult
{
    public string Key { get; set; } = "";
    public string Content { get; set; } = "";
    public string Category { get; set; } = "";
    public float Score { get; set; }
    public string Timestamp { get; set; } = "";

    public override string ToString() => $"[{Category}] {Key} (score: {Score:F3})";
}